### ISSUE TITLE
Task: Ensure the EOS Demo is reformated to the Ersilia Pack version

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos-demo#1]
Hi!

We have entirely re-done the Ersilia Model Hub incorporation template to work with Fast API instead of BentoML. We now need to change this example to use the new template so users can try it out

**Comment by GemmaTuron** [comment]
Please @DhanshreeA try out the Demo model if you have reformated it already

**Comment by DhanshreeA** [comment]
The demo is completely reformatted, and incorporated here: https://github.com/ersilia-os/eos4xq2

Closing this issue now.
